package model;

import java.util.ArrayList;
import java.util.Date;

/**
 * Transports a tweetObject and stores
 * all information generated by the preprocessor.
 *
 * TransportObjects allow the RTSIndices to directly
 * insert tweetIDs without stemming the tweet's content
 * or calculating the significance.
 */
public class TransportObject {

    private TweetObject tweetObject;

    /*
     * Fields populated by the preprocessor
     */

    // preprocessor needs to insert the tweet into the
    // TweetDictionary and store the fetched tweetID here
    private int tweetID;

    // preprocessor needs to stem the tweet's content (e.g. via the Stanford Stemming
    // library, insert each term into the TermDictionary and then store the list
    // of termIDs here)
    private ArrayList<String> termIDs;

    // can probably just be copied from the tweet by the preprocessor
    private Date timestamp;

    // needs to be calculated somehow by the preprocessor
    private float significance;

    // Add more fields if necessary during preprocessor implementation



    /*
     * Constructor and Getters/Setters
     */
    public TransportObject(TweetObject tweetObject) {
        this.tweetObject = tweetObject;
    }

    public TweetObject getTweetObject() {
        return tweetObject;
    }

    public int getTweetID() {
        return tweetID;
    }

    public void setTweetID(int tweetID) {
        this.tweetID = tweetID;
    }

    public ArrayList<String> getTermIDs() {
        return termIDs;
    }

    public void setTermIDs(ArrayList<String> termIDs) {
        this.termIDs = termIDs;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public float getSignificance() {
        return significance;
    }

    public void setSignificance(float significance) {
        this.significance = significance;
    }

}
